name: PR for latest Syft release
on:
  schedule:
    # 7:04 UTC (2:04 am EST)
    - cron: "4 7 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upgrade-syft:
    runs-on: ubuntu-latest
    if: github.repository == 'anchore/sbom-action'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Get latest Syft version
        id: latest-version
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          LATEST_VERSION=$(gh release view --json name -q '.name' -R anchore/syft)
          echo "export const VERSION = \"$LATEST_VERSION\";" > src/SyftVersion.ts
          # install husky hooks and dependencies:
          npm install
          # export the version for use with create-pull-request:
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          signoff: true
          delete-branch: true
          branch: auto/latest-syft
          labels: dependencies
          commit-message: "chore(deps): update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          title: "chore(deps): update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          body: "Update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          token: ${{ steps.generate-token.outputs.token }}
